import { type Restaurant, type Category, type Dish } from '$lib/types/menu.types';

export const seedData = {
  userEmail: 'chico10117@gmail.com',
  restaurant: {
    name: 'Santō',
    logo: '' // Will be generated by DALL-E
  },
  categories: [
    {
      name: 'Starters',
      dishes: [
        {
          title: 'Miso Soup',
          price: '5.00',
          description: 'Shiitake, tofu, negi & wakame',
          imageUrl: ''
        },
        {
          title: 'Truffled Edamames',
          price: '10.00',
          description: 'Edamame beans with truffle',
          imageUrl: ''
        },
        {
          title: 'Seaweed Salad',
          price: '8.00',
          description: 'Traditional Japanese seaweed salad',
          imageUrl: ''
        },
        {
          title: 'Shishito Peppers',
          price: '11.00',
          description: 'Padron peppers with our special house sauce [slightly spicy] and furikake',
          imageUrl: ''
        }
      ]
    },
    {
      name: 'Sashimi',
      dishes: [
        {
          title: 'Santo Tiradito Hamachi',
          price: '20.00',
          description: 'Hamachi covered in our "tiradito" style sauce over shiso leaf and house radish (8 piece)',
          imageUrl: ''
        },
        {
          title: "Chu'toro",
          price: '19.00',
          description: 'Semi-fatty tuna over shiso leaf and house radish',
          imageUrl: ''
        },
        {
          title: "O'toro Seared",
          price: '22.00',
          description: 'Fatty tuna seared with binchotan charcoal, over shiso leaf and house radish',
          imageUrl: ''
        },
        {
          title: 'Truffled Zucchini',
          price: '15.00',
          description: 'Thin grilled zucchini slices with truffle tartare and salt grains',
          imageUrl: ''
        },
        {
          title: 'Salmon Sashimi',
          price: '16.00',
          description: 'Salmon, shiso leaf and daikon radish',
          imageUrl: ''
        }
      ]
    },
    {
      name: 'Nigiris',
      dishes: [
        {
          title: 'Akami',
          price: '7.00',
          description: 'Lean tuna with Nikkiri & wasabi (1 piece)',
          imageUrl: ''
        },
        {
          title: "Chu'toro Nigiri",
          price: '9.00',
          description: 'Semi-fatty tuna with Nikkiri & ginger (1 piece)',
          imageUrl: ''
        },
        {
          title: "O'toro Nigiri",
          price: '12.00',
          description: 'Fatty tuna with Nikkiri & wasabi (1 piece)',
          imageUrl: ''
        },
        {
          title: 'Salmon Yuzu',
          price: '7.00',
          description: 'Salmon with Lemon & yuzukosho (1 piece)',
          imageUrl: ''
        },
        {
          title: 'Unagi',
          price: '7.00',
          description: 'Seared eel with a touch of tare (1 piece)',
          imageUrl: ''
        }
      ]
    },
    {
      name: 'Rolls',
      dishes: [
        {
          title: 'Double Dragon Roll',
          price: '19.00',
          description: 'Tempura shrimp, asparagus and tare sauce, avocado, bonito flakes inside. Covered in our mango-truffle sauce (8 pieces)',
          imageUrl: ''
        },
        {
          title: 'San-Shake',
          price: '18.00',
          description: 'Fresh salmon, crispy salmon skin & ikura with a hint of yuzu (6 pieces)',
          imageUrl: ''
        },
        {
          title: 'Daruma Roll',
          price: '19.00',
          description: 'Soft Shell crab & avocado inside. Masago and tare sauce outside (8 pieces)',
          imageUrl: ''
        },
        {
          title: 'Veggie Dragon Roll',
          price: '16.00',
          description: 'Tempura style asparagus & enoki mushrooms inside. Mango-truffle sauce, grated coconut and sesame seeds on the outside',
          imageUrl: ''
        },
        {
          title: 'Spicy Tuna Roll',
          price: '18.00',
          description: 'Avocado inside. Spicy tuna, negi, crispy tempura flakes & tare sauce on the outside (8 pieces)',
          imageUrl: ''
        }
      ]
    },
    {
      name: 'Wine - Red',
      dishes: [
        {
          title: 'Gulp Hablo/Garnacha',
          price: '14.00',
          description: 'Chilled red',
          imageUrl: ''
        },
        {
          title: 'Oeno/Pinot Noir',
          price: '55.00',
          description: 'Bottle',
          imageUrl: ''
        }
      ]
    },
    {
      name: 'Wine - White',
      dishes: [
        {
          title: 'Furlani/Bianco Alpino',
          price: '50.00',
          description: 'Bottle',
          imageUrl: ''
        },
        {
          title: 'Staffa Conestabile/Bianco',
          price: '58.00',
          description: 'Bottle',
          imageUrl: ''
        },
        {
          title: 'Echeverria No Es Pituko/Chardonay',
          price: '14.00',
          description: 'By the glass',
          imageUrl: ''
        }
      ]
    },
    {
      name: 'Wine - Skin Contact',
      dishes: [
        {
          title: 'Las Jaras Superbloom/Rosé',
          price: '65.00',
          description: 'Bottle',
          imageUrl: ''
        },
        {
          title: 'Roseus/Rosé',
          price: '55.00',
          description: 'Bottle',
          imageUrl: ''
        },
        {
          title: 'Doralice/Orange',
          price: '60.00',
          description: 'Bottle',
          imageUrl: ''
        },
        {
          title: 'Echeverria No Es Pituko/Rosé',
          price: '14.00',
          description: 'By the glass',
          imageUrl: ''
        },
        {
          title: 'Gulp Hablo/Orange',
          price: '14.00',
          description: 'By the glass',
          imageUrl: ''
        }
      ]
    },
    {
      name: 'Sparkling Wine',
      dishes: [
        {
          title: 'García Pérez/Pet Nat Ancestral',
          price: '40.00',
          description: 'Bottle',
          imageUrl: ''
        },
        {
          title: 'Between Us/Pet Nat Rosé',
          price: '70.00',
          description: 'Bottle',
          imageUrl: ''
        }
      ]
    },
    {
      name: 'Hot Drinks',
      dishes: [
        {
          title: 'Decaf',
          price: '5.00',
          description: 'Coffee',
          imageUrl: ''
        },
        {
          title: 'Espresso',
          price: '5.00',
          description: 'Coffee',
          imageUrl: ''
        },
        {
          title: 'Americano',
          price: '6.00',
          description: 'Coffee',
          imageUrl: ''
        },
        {
          title: 'Matcha tea',
          price: '5.00',
          description: 'Green tea powder',
          imageUrl: ''
        },
        {
          title: 'Camomile tea',
          price: '4.00',
          description: 'Herbal tea',
          imageUrl: ''
        },
        {
          title: 'Mint tea',
          price: '4.00',
          description: 'Herbal tea',
          imageUrl: ''
        }
      ]
    },
    {
      name: 'Cold Drinks',
      dishes: [
        {
          title: 'Cascade still water',
          price: '9.00',
          description: '28 oz.',
          imageUrl: ''
        },
        {
          title: 'Iced tea',
          price: '5.00',
          description: 'House-made iced tea',
          imageUrl: ''
        }
      ]
    },
    {
      name: 'Sodas',
      dishes: [
        {
          title: 'Mexican Coke',
          price: '6.00',
          description: 'Made with real sugar',
          imageUrl: ''
        },
        {
          title: 'Diet Coke',
          price: '4.00',
          description: 'Sugar-free',
          imageUrl: ''
        },
        {
          title: 'Topo Chico',
          price: '6.00',
          description: 'Sparkling mineral water',
          imageUrl: ''
        },
        {
          title: 'Sprite',
          price: '4.00',
          description: 'Lemon-lime soda',
          imageUrl: ''
        }
      ]
    },
    {
      name: 'Beer',
      dishes: [
        {
          title: 'Sapporo draft',
          price: '9.00',
          description: 'Japanese lager',
          imageUrl: ''
        },
        {
          title: 'Asahi',
          price: '8.00',
          description: 'Japanese lager',
          imageUrl: ''
        },
        {
          title: 'Corona',
          price: '8.00',
          description: 'Mexican lager',
          imageUrl: ''
        },
        {
          title: 'Pacifico',
          price: '8.00',
          description: 'Mexican lager',
          imageUrl: ''
        },
        {
          title: 'Best Day non alcoholic pilsner',
          price: '10.00',
          description: 'Non-alcoholic beer',
          imageUrl: ''
        },
        {
          title: 'Sky Duster IPA',
          price: '10.00',
          description: 'India Pale Ale',
          imageUrl: ''
        },
        {
          title: 'Sky Duster super dry lager',
          price: '10.00',
          description: 'Japanese-style dry lager',
          imageUrl: ''
        }
      ]
    },
    {
      name: 'Sake',
      dishes: [
        {
          title: 'Nigori',
          price: '65.00',
          description: '500 ml',
          imageUrl: ''
        },
        {
          title: 'Green Ridge',
          price: '35.00',
          description: '300 ml',
          imageUrl: ''
        },
        {
          title: 'Heart of Oak',
          price: '70.00',
          description: '720 ml',
          imageUrl: ''
        },
        {
          title: 'Heart and Soul',
          price: '80.00',
          description: '720 ml',
          imageUrl: ''
        },
        {
          title: 'Fair Maiden',
          price: '75.00',
          description: '500 ml',
          imageUrl: ''
        },
        {
          title: 'Ohmine Shuzo',
          price: '90.00',
          description: '720 ml',
          imageUrl: ''
        },
        {
          title: 'Shibata pink nigori flask',
          price: '30.00',
          description: '200 ml',
          imageUrl: ''
        },
        {
          title: 'Shibata black junta ginjo flask',
          price: '30.00',
          description: '200 ml',
          imageUrl: ''
        },
        {
          title: 'House sake 1/2 carafe',
          price: '25.00',
          description: '250 ml',
          imageUrl: ''
        },
        {
          title: 'House sake full carafe',
          price: '45.00',
          description: '500 ml',
          imageUrl: ''
        }
      ]
    }
  ]
};
