import { type Restaurant, type Category, type Dish } from '../../src/lib/types/menu.types';

export const seedData = {
  userEmail: 'chico10117@gmail.com',
  restaurant: {
    name: 'Ozman Kebab2',
    logo: '', // Will be generated by DALL-E
    customPrompt: `
OZMAN KEBAB

ESPECIALIDADES:
- Kebab tradicional
- Durum artesanal
- Pizza turca
- Platos combinados
- Pollo frito crujiente

HORARIO DE APERTURA:
12:30 a 17:00h y de 19:00 a 00:00h

MEDIOS DE PAGO:
Visa, MasterCard

SERVICIO A DOMICILIO
Pedido mínimo: 10€
`
  },
  categories: [
    {
      name: 'KEBAB',
      dishes: [
        {
          title: 'Kebab Tradicional de Ternera y Pollo',
          price: '4.50',
          description: 'Pan de pita artesanal relleno de jugosa carne mixta de ternera y pollo asada al estilo tradicional, acompañado de ensalada fresca y salsas caseras',
          allergens: ['gluten']
        },
        {
          title: 'Kebab Crujiente Especial',
          price: '4.50',
          description: 'Pan de pita tostado con carne mixta crujiente, verduras frescas y una selección de nuestras salsas especiales',
          allergens: ['gluten']
        },
      ]
    },
  ]
}; 